{
    "errno"
:
    0, "message"
:
    {
        "total"
    :
        [{
            "userid": "217121",
            "openid": "EXSLv6vOMSI8u6zmecmuX6Xmo7csosch",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "217116",
            "openid": "f87yqV77xqA0KIWiP668JHvYkQqnLyhY",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "217122",
            "openid": "gzkGvCZaaitNvtIfHanwagfafWb3KH3z",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "217119",
            "openid": "j6TVNJ0f8hY1PVHn8fE61TF2Ysey8Hey",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "217117",
            "openid": "kYuuPFNRNnnN99yuFEn1UYpOS1uqsooe",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "217120",
            "openid": "lqZqLXqNcgHW8P96466hx3a436C8CXGW",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }, {
            "userid": "1332",
            "openid": "oCwP-5-cDSb2PPesQPXjkOL0eBSk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u963f\u767d",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1327",
            "openid": "oCwP-5-OvcD2vk-TkPvYeOJghBCk",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "\u7f9a\u7f8a\u4e92\u52a8-\u5434\u9633",
            "sex": "0",
            "binddata": []
        }, {
            "userid": "1873",
            "openid": "oCwP-5--MoTwMgyKdz5W7vEsB5iM",
            "avatar": "http://www.chaoyong666.com/jiang/img.png",
            "nickname": "Chris",
            "sex": "1",
            "binddata": []
        }], "count"
    :
        "71"
    }
}